In [1]:
import numpy as np
arr=np.array([2,3,4,5])
print(arr +5)

[ 7  8  9 10]


In [2]:
import numpy as np
arr=np.array([[10,20],[20,30],[40,50]])
print(arr +[5])

[[15 25]
 [25 35]
 [45 55]]


In [4]:
import numpy as np
arr=np.array([[10,20],[20,30],[40,50]])
print(arr +[5,6])

[[15 26]
 [25 36]
 [45 56]]
