In [1]:
import re
text="python is easy"
result=re.search("python", text)
print(result)

<re.Match object; span=(0, 6), match='python'>


In [2]:
import re
text="i have 10 books 20 pens"
result=re.findall(r"\d", text)
print(result)

['1', '0', '2', '0']


In [3]:
import re
text="i have 10 books 20 pens"
result=re.findall(r"\d+", text)
print(result)

['10', '20']


In [4]:
import re
text="python programming"
result=re.match("python",text)
print(result.group())

python


In [5]:
import re
text="python,java,css"
result=re.split(",",text)
print(result)

['python', 'java', 'css']


In [1]:
import re
text="python programming"
result=re.sub("python","java",text)
print(result)

java programming


In [3]:
import re
text="my age is 20"
result=re.search("\d+",text)
print(result)

<re.Match object; span=(10, 12), match='20'>


In [4]:
import re
text="my age is 20"
result=re.findall(r"\d+",text)
print(result)

['20']


In [10]:
import re 
email = "xyz@gmail.com"
pattern=r'^[a-zA-Z0-9]+@[a-zA]+\.[a-zA]+$'
if re.match(pattern,email):
    print("valid")
else:
    print("Invalid")

valid


In [11]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[[1,3]])

[20 40]


In [12]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [13]:
import numpy as np
marks = np.array([30,50,60,80])
print(marks[marks>50])

[60 80]


In [14]:
import numpy as np
arr=np.array([[10,20],[30,40],[40,50]])
for row in arr:
    print(row)

[10 20]
[30 40]
[40 50]


In [15]:
for i in np.nditer(arr):
    print(i)

10
20
30
40
40
50


In [16]:
import numpy as np
a = "srinidhi"
b = "goud"
c = (a+b)
print(c)

srinidhigoud


In [17]:
import numpy as np
arr=np.array([10,20,30,40,50])
x=np.where(arr==20)
print(x)

(array([1]),)


In [18]:
import numpy as np
arr=np.array([10,20,30,40,50])
x=np.sort(arr==10)
print(x)

[False False False False  True]


In [19]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
c=(a+b)
print(c)

[11 22 33 44]


In [22]:
import numpy as np
marks=np.array([40,35,60,80,75])
result=list(filter(lambda marks:marks%2==0,marks))
print(marks[marks>=45])

[60 80 75]
