In [1]:
try:
    num = input("Enter your name")
except NameError:
    print("write characters only")
    

Enter your name srinidhi


In [2]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [4]:
arr = np.array([[10,20], [20,30], [40,8]])
print(arr)

[[10 20]
 [20 30]
 [40  8]]


In [5]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(arr*2)

[10 20 30 40 50]
[ 20  40  60  80 100]


In [6]:
import numpy as np
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [7]:
abc = np.array([10,20,30,40])
print(np.max(abc))

40


In [21]:
def count(n):
    if n==0:
       return
    print(n)
    count(n-1)
count(5)

5
4
3
2
1


In [22]:
for i in range(5):
    print("Hello")

Hello
Hello
Hello
Hello
Hello


In [34]:
def fact(n):
    if (n==1):
         return 1
        
    return n*fact(n-1)
print(fact(5))

120


In [35]:
def square(x):
    return x*x
print(square(6))

36


In [36]:
square = lambda x:x*x
print(square(3))

9


In [37]:
mul = lambda a,b:b*a
print(mul(5,2))

10


In [38]:
check = lambda num:"Even" if num%2==0 else "Odd"
print(check(10))

Even


In [39]:
check = lambda num:"Even" if num%2==0 else "Odd"
print(check(7))

Odd


In [41]:
student=[("Ram",80), ("ravi",75), ("mahesh",35)]
result=sorted(student, key=lambda x:x[1])
print(result)

[('mahesh', 35), ('ravi', 75), ('Ram', 80)]
