In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.vstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
import numpy as np
a=np.array([5,6,7,8])
b=np.array([9,10,11,12])
print(np.hstack((a,b)))

[ 5  6  7  8  9 10 11 12]


In [6]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([11,22,33,44])
print(np.dstack((a,b)))

[[[ 1 11]
  [ 2 22]
  [ 3 33]
  [ 4 44]]]
